"""empty message

Revision ID: 07faeef53a6f
Revises: 4890ddcedffd
Create Date: 2025-09-08 09:47:50.666995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07faeef53a6f'
down_revision = '4890ddcedffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autorizados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=150), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('autorizados')
    # ### end Alembic commands ###
