"""empty message

Revision ID: 1a728e8abc42
Revises: 4890ddcedffd
Create Date: 2025-09-16 15:28:41.874256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a728e8abc42'
down_revision = '4890ddcedffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividades_medico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actividades_medico')
    # ### end Alembic commands ###
