"""empty message

Revision ID: 30ca324517f3
Revises: 78913ea870f8
Create Date: 2025-09-06 09:53:29.666424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ca324517f3'
down_revision = '78913ea870f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_column('password')

    with op.batch_alter_table('medicos', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
