"""empty message

Revision ID: 5963df2c002f
Revises: db87b6b959f1
Create Date: 2025-09-23 16:10:50.845127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5963df2c002f'
down_revision = 'db87b6b959f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividades_medico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_inicio', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('fecha_fin', sa.DateTime(), nullable=False))
        batch_op.drop_column('fecha')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividades_medico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('fecha_fin')
        batch_op.drop_column('fecha_inicio')

    # ### end Alembic commands ###
