"""empty message

Revision ID: db87b6b959f1
Revises: 1a728e8abc42
Create Date: 2025-09-18 16:42:07.020460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db87b6b959f1'
down_revision = '1a728e8abc42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividades_medico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.Date(), nullable=False))
        batch_op.drop_column('fecha_fin')
        batch_op.drop_column('fecha_inicio')

    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.Date(), nullable=False))
        batch_op.drop_column('fecha_fin')
        batch_op.drop_column('fecha_inicio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fecha_fin', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('fecha')

    with op.batch_alter_table('actividades_medico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fecha_fin', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('fecha')

    # ### end Alembic commands ###
